### ISSUE TITLE
i18n redesign and example

### ISSUE THREAD

**Issue by obasilakis** [dominant-strategies/quaipay#74] opened 2023-05-31 13:03 UTC

**Comment by juanmanso** [comment] 2023-07-26 09:29
This task's goal is still the same, but now we shall focus on the structure and then do the migration of visible text.

From our DX we found that locales are flexible in structure and since we didn't develop a convention, they would be harder to hand over to a translator.

Thus we are going to research a bit how we could structure the i18n and localization interface with designers and content writers while also keeping it clean for developers.

**Comment by juanmanso** [comment] 2023-07-27 14:26
# 📣 RFC 📣 <br/> 🌐 Design of i18n framework and DX

## 🤔 Why?

As the project starts to grow in size, more and more screens are going to be developed and revamped.

Since having localization is a requirement, but also since hardcoded strings will be come a pain point when scaling the product to other markets, having this framework properly setup is a must.

## 🎯 Goal

Our goal is to have a "good-enough" solution that enables us to scale and develop quickly without exposing ourselves to a future big refactor down the road.

We do not aim for the ultimate solution but rather one that can be solid enough to be the starting point for upcoming improvements.

Additionally, we want to create a framework that helps us detach from other areas (i.e. design + content writing or translations). By this we mean that the framework should set a couple of ground rules so everyone in the team understands how to develop it but also what to expect or ask as input.

Lastly, we want to improve developer experience (DX) so that we minimize:

- Back and forth with the non-tech team about copies
- Impact of screens and components refactors due to technical or product decisions
- Overhead of adding translations for languages that are not the primary one (generally English)

## 🧩 Things to figure out

- Folder structure
  - Where should translation (t9n) files be stored
  - Where should reference strings (the ones provided by design, i.e. english) be stored
    - Do they need to be close to the screen/component?
    - Should we do a monolithic file (like the one we have now)?
  - How to store the whole l10n database in an object to be used by the i18n framework as a resource
- Naming
  - How should we name things both on development and in design (convention)
- Shared strings
  - How to determine when a string or phrase should be treated as common
  - How to maintain common strings or phrases

### 🚫 Out of scope

- Schema typing
- Check for unused strings
- Automated &/or automatic updates

## 💍 Proposal

In the following section we share our research and proposed solutions.

<div class="warning" style='background-color:#DDEDEA; color: #0E7B6C; border-left: solid #1F8C7D 4px; border-radius: 4px; padding:0.7em;'>
<span>
<p style='margin-top:1em; text-align:center'>
<i><b>tl;dr</b></i></p>
<p style='margin-left:1em;'>
<ul>
  <li> For folder structure:<ul>
    <li> Keep english strings close to the components (favoring component driven design)
    <li> Translation strings will be dumped into a single file to be crafted by translators and tools (i.e. scripts) </ul>
  <li> For naming:<ul>
    <li> Simple and concise
    <li> Leverage on the context of the screen/component </ul>
  <li> For shared strings:<ul>
    <li> Insert them inside the strings file rather than the tsx
    <li> Assert if it is used more than 3 times in different scopes (i.e. flows) <ul>
      <li> If used multiple times in the same scope of feature, move it upstream
      <li> If shared across scopes/flows, move it to common file </ul>
    </ul>
</ul>
</p></span>
</div>

### 🗂️ Folder Structure

<details>
<summary><i>Click to expand/collapse explanation</i></summary>
<br>

**Since one of our goals is to decrease DX friction with this matter, we first propose to keep strings as close as possible with the component (as we do styles and types)**.

When adding a string to a screen or component we shall do the following:

```ts
// in SomeComponent.string.ts next to SomeComponent.tsx
export const someComponentStrings = {
  title: 'This is a title',
  description: 'This is a description',
};
```

Then we shall bubble it up the next level of abstraction and use it there.

- For shared components we expect the text to be determined by their parent so if a `string.ts` shows up, it's a clear indicator that either it shouldn't be shared or a refactor must take place.
- For screens or their internal components, strings should be bubbled to their corresponding object.

A demonstration of this case can be seen below, where the screen `SomeOnboardingScreen` has strings associated with it:

```ts
// in `strings.ts` inside the onboarding folder
import { SomeOnboardingScreenStrings } from './SomeOnboardingScreen.strings';

export const onboarding = {
  SomeOnboardingScreen: SomeOnboardingScreenStrings,
};
```

> _From this point onwards, the developer should not go any further to add the new string. Just for the purpose of this documentation, we will illustrate how the process continues if this flow were to be initialized for the first time._

Then, that file will be imported in `src/locales/en.ts` as we did before:

```ts
import { onboarding } from 'src/onboarding/strings';

export const en = {
  translation: {
    onboarding,
  },
};
```

Finally, on `src/locales/index.ts` we do the final import:

```ts
import { de } from './de'
import { en } from './en'

...

i18n.use(initReactI18next).init({
  resources: {
    de,
    en,
  },
  ...
})
```

On a side note, non-reference string objects (such as german in the case of this example) shall live alongside `en`

```
src
  |- ...
  |_ locales
    |
    |- index.ts
    |- en.ts
    |_ de.ts
```

`de.ts` will contain all the translation strings in a raw big object. This object shall be crafted using additional tools/scripts that should be determined in the future. For now, we just know decide that they are going to be stored there.

</details>

### 👶 Naming

<details> 
<summary>
<i>Click to expand/collapse the explanation</i>
</summary>
<br>

Naming is always an interesting topic in development. To keep things simple these are the rules for naming keys to be used as l10n strings:

- Keep them simple
- No more than a couple of words
- Use the context of the environment to keep them concise

For example:

```ts
export const HomeScreenStrings = {
  // No need to put homeTitle since it's common sense
  // to infer it from the screen name
  title: 'Home',
  // Despite having only one button in this example,
  // name it for easier undestanding when reading the code
  continueButton: 'Continue',
  // Since there's only 1 learn more, no need to specify what is to be learned
  learnMore: 'Learn more about our newest product that is awesome',
  // No need to explain much about the disclaimer, just
  // be concise and put a representative word to it
  termsDisclaimer: 'You are using the app under our terms and conditions',
  screenshotDisclaimer: 'For security reasons, screenshots are disabled',
};
```

</details>

### 🤝 Shared strings

<details>
<summary>
<i>Click to expand/collapse the explanation</i>
</summary>
<br>

Repeated text is a pain point for development and translation since it's used across the app and makes code structure ends up being entangled.

Our solution is quiet simple. Instead of using the common namespace in our components (as we do now and we call `t(common.continue)`), we should entirely remove it from our components.

Instead, common strings will be referred used internally and referred using _nesting_. With that we detach the components from the `common` abstraction while keeping it abstracted but in the i18n level

Below, you can find an example that illustrates what we propose leveraging on the power of _nesting_ from i18next dependency:

```ts
// in src/locales/en.ts

export const en = {
    common: {
        continue: 'Continue',
        from: 'From',
        ...
    },
    ...
}
```

```ts
// in src/home/receive/ReceiveAmountInputScreen.strings.ts

export const ReceiveAmountInputScreenStrings = {
  continue: '$t(common.continue)',
  ...
};
```

```tsx
// in src/home/receive/ReceiveAmountInputScreen.tsx

...

const { t } = useTranslation('translation', {
    keyPrefix: 'home.receive.amountInput'
})

return (
    ...
    <QuaiPayButton
    title={t('continue')}
    >
)
```

With this 3 snippets we can show common strings in different screens but the TSX doesn't know they are shared. That abstraction makes code cleaner and also detached from any other usage of it.

Lastly, to determine if a string should be moved to `common` use the following criteria:

- Is the string used several times **in the same flow**?
  - If true, move it upstream to the highest level until shared
  - This is usually what happens for screens inside the same flow, for example, onboarding, settings, receive, send, etc.
- Is the string used several times **across flows**?
  - If true, move it to `common` and use nesting to access it in their respective components/screens

</details>

**Comment by juanmanso** [comment] 2023-07-28 11:50
Since the team approved the proposal, we changed the title of the issue to focus on the proposal and creating a PR with an example usage.

Full migration will be done in a new task

**Closed** 2023-07-31 08:26 UTC
